services:
  app:
    image: "ghcr.io/open-webui/open-webui:v0.11.2"
##    ports: ## not needet when using network mode host
##      - "8080:8080"
    network_mode: "host"
    volumes:
      - "/open-webui:/app/backend/data"
    env_file:
      - ".env"
    restart: "unless-stopped"
