services:
  app:
    build: .
    environment:
      TZ: "Europe/Brussels"
    volumes:
      - "${BASEPATH}/twitch-recorder/data:/app/data:z" ## Video Files from Twitch Recorder
    restart: unless-stopped
##    ports:
##      - "3000:3000"
    networks:
      system_internal:

networks:
  system_internal:
    external: true

