version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/kuma"
      - "/network"
      - "/nextcloud"
      - "/nginx"
      - "/paperless-ngx"
      - "/portainer-ee"
      - "/wordpress"
    schedule:
      interval: "daily"
