version: 2
updates:
  - package-ecosystem: "docker-compose"
    target-branch: "master"
    directories:
      - "**/*"
    schedule:
      interval: "daily"

  ## Main
  - package-ecosystem: "docker-compose"
    target-branch: "main"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "FM"

  - package-ecosystem: "docker"
    target-branch: "main"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "FM"

  ## Xenon 
  - package-ecosystem: "docker-compose"
    target-branch: "xenon"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "Xenon"

  - package-ecosystem: "docker"
    target-branch: "xenon"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "Xenon"

  ## Opal
  - package-ecosystem: "docker-compose"
    target-branch: "opal"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "Opal"

  - package-ecosystem: "docker"
    target-branch: "opal"
    directories:
      - "**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
      - "Opal"
