version: 2
updates:
  - package-ecosystem: "docker-compose"
    directories:
      - "/bind9"
      - "/bookstack"
      - "/caddy"
      - "/code-server"
      - "/compose"
      - "/funkwhale"
      - "/grafana"
      - "/habormaster"
      - "/heimdall"
      - "/hetzner-ddns"
      - "/homarr"
      - "/invidious"
      - "/it-tools"
      - "/jellyfin"
      - "/jet.ddns.net"
      - "/kuma"
      - "/netbox"
      - "/nextcloud"
      - "/nextcloud-aio"
      - "/nginx-proxy-manager"
      - "/paperless"
      - "/paperless-ngx"
      - "/pdf-tools"
      - "/pihole"
      - "/portainer-ce"
      - "/portainer-ee"
      - "/pyload"
      - "/sbw"
      - "/searxng"
      - "/statping-ng"
      - "/tandoor"
      - "/unbound"
      - "/vaultwarden"
      - "/viewtube"
      - "/watchtower"
      - "/wordpress"
      - "/xbrowsersync"
      - "/zabbix"
    schedule:
      interval: "daily"
