# Global doco-cd configuration
# This file enables auto-discovery for all stacks in the repository.

# Auto-discovery will find every subdirectory with a docker-compose.yml
# and deploy it as a stack.
auto_discovery:
  enabled: true
  depth: 1
  delete: true

# These settings are inherited by all discovered stacks.
# By listing secrets.env here, doco-cd will automatically try to 
# find and decrypt it for every stack if it exists.
##env_files:
##  - .env
##  - secrets.env

environment:
  BASEPATH: /data
  TZ: Europe/Brussels

#repository_url: https://github.com/HJF9w/docker-bookstack.git
#reference: master
