version: "2.3"
services:

  app:
    image: "caddy:latest"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/srv:/srv"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/data"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/config:/config"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://google.com || exit 1"]
      timeout: 2s
      interval: 1m
      retries: 1
      start_period: 10s
    networks:
      system_mac_vlan:
        ipv4_address: "${EXT_IPV4}"
      system_internal:

networks:
  system_internal:
    external: true
  system_mac_vlan:
    external: true



