services:
  app:
    build: .
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile:ro"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/srv:/srv"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/data"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/config:/config"
    restart: always
    env_file:
      - ".env"
      - "secrets.enc.env"
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:2019/config/ || exit 1"]
      timeout: 2s
      interval: 1m
      retries: 1
      start_period: 10s
    networks:
      system_mac_vlan:
        ipv4_address: "${EXT_IPV4}"
        mac_address: "86:D0:BD:81:3B:92"
      system_internal:
      to_adsb:
      to_forgejo:

networks:
  system_internal:
    external: true
  system_mac_vlan:
    external: true
  to_adsb:
  to_forgejo:

