#!/usr/bin/env bash
set -euo pipefail

# Entrypoint for the container.
# If CRON_EXPR is empty/unset -> run once and exit.
# Otherwise write /etc/crontabs/root with the CRON_EXPR and start crond.

CRON_EXPR="${CRON_EXPR:-}"
LOG_DIR="/logs"
RUNNER="/usr/local/bin/tl_conv.py"

# Ensure log dir exists
mkdir -p "${LOG_DIR}"

# Ensure timezone is set for the container
if [ -n "${TZ:-}" ]; then
  if [ -f "/usr/share/zoneinfo/${TZ}" ]; then
    ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime
    echo "${TZ}" > /etc/timezone || true
    echo "Timezone set to ${TZ}"
  else
    echo "Warning: timezone ${TZ} not found in container tzdata; leaving default"
  fi
fi

if [ -z "${CRON_EXPR}" ]; then
  echo "CRON_EXPR is empty/unset -> running once and exiting."
  exec "${RUNNER}"
else
  echo "Installing crontab with expression: ${CRON_EXPR}"
  # Write crontab for root (busybox crond style)
  # Redirecting stdout/stderr to /proc/1/fd/1 and 2 allows output to show up in docker logs
  cat > /etc/crontabs/root <<EOF
# generated by entrypoint
${CRON_EXPR} ${RUNNER} >> /proc/1/fd/1 2>> /proc/1/fd/2
EOF

  echo "Starting crond in foreground..."
  # -f foreground, -l 8 debug/verbose logging
  exec crond -f -l 8
fi
