version: '3'
services:
  heimdall:
    image: 'linuxserver/heimdall'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - '${basepath}/heimdall:/config'
        #- 'heimdall:/config'
    restart: unless-stopped
    networks:
      fm_internal:
networks:
  fm_internal:
    external: true

