
version: "3"

services:
  app:
    image: "vaultwarden/server"
    environment:
      - WEBSOCKET_ENABLED=true
      #- ADMIN_TOKEN=123 # use to access the /admin pannel
      #  - DOMAIN=https://speicher.ddns.net
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/data/"
    hostname: "${HOSTNAME}"
    restart: always
    networks:
      system_internal:


networks:
  system_internal:
    external: true



