---
services:
  app:
    image: "stirlingtools/stirling-pdf:2.5.2-fat"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/trainingData:/usr/share/tesseract-ocr/4.00/tessdata" #Required for extra OCR languages
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/extraConfigs:/configs"
#      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/customFiles:/customFiles/"
    environment:
      - SECURITY_ENABLELOGIN=false
      - SECURITY_INITIALLOGIN_USERNAME=admin
      - SECURITY_INITIALLOGIN_PASSWORD=admin
      - SYSTEM_DEFAULTLOCALE=de_DE
    networks:
      system_internal:

networks:
  system_internal:
    external: true
