---
services:
  app:
    image: "stirlingtools/stirling-pdf:2.13.0-fat"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/trainingData:/usr/share/tesseract-ocr/4.00/tessdata" #Required for extra OCR languages
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/extraConfigs:/configs"
#      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/customFiles:/customFiles/"
    env_file:
      - ".env"
      - "secrets.enc.env"
    networks:
      system_internal:

networks:
  system_internal:
    external: true
