version: '3'
services:
  mysql:
    image: mysql
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/mysql-data:/var/lib/mysql'

  app:
    image: bookstack:23.12
    build:
      context: ./docker-bookstack
      dockerfile: Dockerfile
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql:3306
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
    - APP_URL=http://localhost
    - APP_KEY=SomeRandomStringWith32Characters
    volumes:
    - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/uploads:/var/www/bookstack/public/uploads'
    - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/storage-uploads:/var/www/bookstack/storage/uploads'
    ports:
    - "8081:8080"
