version: "2"
services:
  db:
    image: 'mariadb' 
    environment:
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD=lol
      - MYSQL_PASSWORD=lol
      - MYSQL_USER=bookstack
      - MYSQL_DATABASE=bookstack
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/db:/config'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/mysql-data:/var/lib/mysql'
    restart: unless-stopped
    networks:
      default:

  app:
    image: 'solidnerd/bookstack:22.04.02'
    environment:
    #set the APP_ to the URL of bookstack without without a trailing slash APP_URL=https://example.com
      - APP_URL=http://localhost
      - DB_HOST=db
      - DB_PASS=lol
      - DB_USER=bookstack
      - DB_DATABASE=bookstack
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/app:/config'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/uploads:/var/www/bookstack/public/uploads'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/storage-uploads:/var/www/bookstack/storage/uploads'
    restart: unless-stopped
    depends_on:
      - db
    networks:
      default:
      xe_internal:

networks:
  xe_internal:
    external: true
  default:

