version: "3"

services:
  app:
    image: ubuntu/bind9@sha256:70b26544bc66e5152319fc2d022fc9f4d4bd8ced31bbba9fdd06ede469a27170
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    volumes:
      - "$PWD/.config:/etc/bind"
      - "$PWD/.cache:/var/cache/bind"
      - "$PWD/.records:/var/lib/bind"
    restart: always
    networks:
      system_mac_vlan:
        ipv4_address: "${EXT_IPV4}"
      system_internal:

networks:
  system_mac_vlan:
    external: true
  system_internal:
    external: true
