services:
  app:
    image: 'ubuntu/bind9:latest'
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    volumes:
      - "$PWD/.config:/etc/bind"
      - "$PWD/.cache:/var/cache/bind"
      - "$PWD/.records:/var/lib/bind"
      - "$PWD/.log:/var/log"
    restart: always
    ports:
      - '53000:53'
