version: "3"
services:
  app:
    #image: quay.io/invidious/invidious:latest-arm64
    image: quay.io/invidious/invidious:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: db
          port: 5432
    ports:
      - "127.0.0.1:3000:3000"
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
#    logging:
#      options:
#        max-size: "1G"
#        max-file: "4"
    networks:
      system_internal:

  db:
    image: postgres:14
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
      - ./sql:/config/sql
      - ./init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]

networks:
  system_internal:
    external: true

volumes:
  data:
