version: "3"
services:
  app:
    # image: "quay.io/invidious/invidious:latest" # X86_64
    image: "quay.io/invidious/invidious:latest-arm64" # ARM64/AArch64 devices
    restart: unless-stopped
    environment:
      # Please read the following file for a comprehensive list of all available
      # configuration options and their associated syntax:
      # https://github.com/iv-org/invidious/blob/master/config/config.example.yml
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: kemal
          password: kemal
          host: db
          port: 5432
        check_tables: true
        # external_port:
        # domain:
        # https_only: false
        # statistics_enabled: false
        hmac_key: "aekee9ahh7AicheiYaec"
        https_only: true
        domain: "invidious.home.arpa"
        external_port: 443
    healthcheck:
      test: wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/comments/jNQXAC9IVRw || exit 1
      interval: 30s
      timeout: 5s
      retries: 2
#    logging:
#      options:
#        max-size: "1G"
#        max-file: "4"
    depends_on:
      - "db"
    networks:
      internal:
      system_internal:

  db:
    image: "postgres:14"
    restart: unless-stopped
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/var/lib/postgresql/data:z"
      - "./sql:/config/sql"
      - "./init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh"
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: kemal
      POSTGRES_PASSWORD: kemal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    networks:
      internal:

networks:
  internal:
  system_internal:
    external: true

volumes:
  data:
