version: '2.3' ## v2 is needet for networking, v2.3 is needet because of healt checks.
services:

  db:
    image: 'postgres'
    restart: 'unless-stopped'
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - '${basepath}/paperless-db/data:/var/lib/postgresql/data'
    networks:
      internal:

  redis:
    image: 'redis'
    restart: 'unless_stopped'
    networks:
      internal:

  gotenberg:
    image: 'thecodingmachine/gotenberg'
    restart: 'unless_stopped'
    environment:
      DISABLE_GOOGLE_CHROME: 1
    networks:
      internal:
    depends_on:
      - paperless_db

  tika:
    image: 'apache/tika'
    restart: 'unless_stopped'
    networks:
      internal:
    depends_on:
      - paperless_db

  app:
    image: 'jonaswinkler/paperless-ng'
    restart: 'unless_stopped'
    environment:
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
    env_file: '.env'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 7s
      timeout: 2s
      retries: 1
      start_period: 10s
    volumes:
      - '${basepath}/paperless/data:/usr/src/paperless/data'
      - '${basepath}/paperless/media:/usr/src/paperless/media'
      - '${basepath}/paperless/export:/usr/src/paperless/export'
      - '${basepath}/paperless/consume:/usr/src/paperless/consume'
    networks:
      internal:
      fm_internal:
    depends_on:
      - 'paperless_tika'


networks:
  fm_internal:
    external: true
  internal:
    driver: 'bridge'
