version: "3"
services:
  navidrome:
    container_name: 'navidrome'
    image: 'deluan/navidrome:latest'
    user: "1000:1000"
    #ports:
    #  - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      #ND_BASEURL: '' ## if used with .../subaddress/
      #ND_ENABLETRANSCODINGCONFIG: 'true'  ## only if you need to change transcoding, not save.
    volumes:
      - '/mnt/data/docker/navidrome:/data'
      - '/mnt/data/music:/music:ro'
    networks:
      xe_internal:

networks:
  xe_internal:
    external: true
