services:
  app:
    image: "grafana/grafana:12.3.1-security-01"
    restart: "unless-stopped"
    user: "472"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/grafana:/var/lib/grafana"
      - "./config.yml:/etc/influxdb2/config.yml"
      - "./grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - "system_internal"

  db:
    image: "influxdb:2.8"
    ports:
      - '8086:8086'
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/influxdb:/var/lib/influxdb2"
    networks:
      - "system_internal"
      - "internal"

networks:
  internal:
  system_internal:
    external: true
