services:
  app:
    image: "grafana/grafana:13.0.1-security-01"
    restart: "unless-stopped"
    user: "472"
    env_file:
      - secrets.enc.env
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/grafana:/var/lib/grafana"
      - "./config.yml:/etc/influxdb2/config.yml"
      - "./grafana.ini:/etc/grafana/grafana.ini"
    networks:
      - "system_internal"

  db:
    image: "influxdb:2.9"
    env_file:
      - secrets.enc.env
    ports:
      - "8086:8086"
    restart: "unless-stopped"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/influxdb:/var/lib/influxdb2"
    networks:
      - "system_internal"
      - "internal"

  postgres:
    image: "postgres:18.3-alpine3.23"
    restart: "unless-stopped"
    env_file:
      - secrets.enc.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-timeseries}
      - POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=${TZ:-UTC}
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/postgres:/var/lib/postgresql"
    networks:
      system_internal:
      internal:
      system_mac_vlan:
        ipv4_address: "${POSTGRES_EXT_IPV4}"

  pgadmin:
    image: "dpage/pgadmin4:2026-05-06-1"
    restart: "unless-stopped"
    env_file:
      - secrets.enc.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - TZ=${TZ:-UTC}
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/pgadmin:/var/lib/pgadmin"
    networks:
      - "system_internal"
      - "internal"

networks:
  internal:
  system_internal:
    external: true
  system_mac_vlan:
    external: true

