services:
  db:
    image: postgres:18.3-alpine3.23
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/db:/var/lib/postgresql
    env_file:
      - ".env"
      - "secrets.enc.env"
    networks:
      default:

  redis:
    image: redis:8.10-alpine3.23
    restart: unless-stopped
    command: /bin/sh -c 'exec redis-server --requirepass "$$REDIS_HOST_PASSWORD"'
    env_file:
      - ".env"
      - "secrets.enc.env"
    depends_on:
      - db
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/redis:/data
    networks:
      default:

  app:
    image: nextcloud:34.0.0-apache
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/app:/var/www/html
    env_file:
      - ".env"
      - "secrets.enc.env"
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - OVERWRITEPROTOCOL=https
      - NC_DEFAULT_PHONE_REGION=DE
      - DEFAULT_PHONE_REGION=DE
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=10G
    depends_on:
      - redis
    networks:
      default:
      system_internal:

  cron:
    image: nextcloud:34.0-apache
    restart: unless-stopped
    env_file:
      - ".env"
      - "secrets.enc.env"
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - redis
    networks:
      default:

  imaginary:
    image: nextcloud/aio-imaginary:20260727_092405
    restart: unless-stopped
    env_file:
      - ".env"
      - "secrets.enc.env"
    environment:
      - PORT=9000
    command: -concurrency 10 -enable-url-source
    networks:
      default:

networks:
  default:
  system_internal:
    external: true
