version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ${basepath}/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    networks:
      default:

  redis:
    image: redis:alpine
    restart: unless-stopped
    depends_on:
      - db
    networks:
      default:

  app:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - ${basepath}/${COMPOSE_PROJECT_NAME}:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TRUSTED_PROXYS=192.168.178.0/24 172.18.0.0/16 10.10.10.0/8
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 127.0.0.1 127.0.1.1 nextcloud.xe
      - OVERWRITEPROTOCOL=https
      - DEFAULT_PHONE_REGION=de
    depends_on:
      - redis
    networks:
      default:
      xe_internal:

  cron:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - ${basepath}/${COMPOSE_PROJECT_NAME}:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - redis
    networks:
      default:

networks:
  default:
  xe_internal:
    external: true
