version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - ${basepath}/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      default:

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    networks:
      default:

  app:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - ${basepath}/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - TRUSTED_PROXYS=192.168.178.0/24 172.18.0.0/16 10.10.10.0/8
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 127.0.0.1 127.0.1.1
    depends_on:
      - db
      - redis
    networks:
      default:

  cron:
    image: nextcloud:apache
    restart: unless-stopped
    volumes:
      - ${basepath}/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      default:


  proxy:
    image: 'jc21/nginx-proxy-manager'
    restart: unless-stopped
    ports: 
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - '${basepath}/nextcloud_nginx/data:/data'
      - '${basepath}/nextcloud_nginx/letsencrypt:/etc/letsencrypt'
    networks:
      default:

networks:
  default:
