services:
  db:
    image: postgres:18.3-alpine3.23
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/db:/var/lib/postgresql
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      default:

  redis:
    image: redis:8.6-alpine3.23
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    depends_on:
      - db
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/redis:/data
    networks:
      default:

  app:
    image: nextcloud:33.0.3-apache
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/app:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_TRUSTED_DOMAINS}
      - TRUSTED_PROXIES=${TRUSTED_PROXIES}
      - OVERWRITEHOST=${NEXTCLOUD_HOST}
      - OVERWRITEPROTOCOL=https
      - NC_DEFAULT_PHONE_REGION=DE
      - DEFAULT_PHONE_REGION=DE
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=10G
    depends_on:
      - redis
    networks:
      default:
      system_internal:

  cron:
    image: nextcloud:33.0-apache
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - redis
    networks:
      default:

  imaginary:
    image: nextcloud/aio-imaginary:20260409_094910
    restart: unless-stopped
    environment:
      - PORT=9000
    command: -concurrency 10 -enable-url-source
    networks:
      default:

networks:
  default:
  system_internal:
    external: true
