version: '3.8'
services:
  app:
    image: "trafex/php-nginx"
    restart: unless-stopped
    volumes:
      - "$PWD/html:/var/www/html:ro,z"
    ports:
      - "8080:8080"

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: pw4root
      MARIADB_USER: user
      MARIADB_PASSWORD: pw4user
      MARIADB_DATABASE: sbw

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8888:8080

