version: "2"
services:
  app:
    image: "portainer/portainer-ee"            ## Business version
    restart: always
    #ports:
    #  - "8000:8000"
    #  - "9000:9000"
    healthcheck:
      test: curl --fail http://127.0.0.1:8000 || exit 1
      timeout: 2s
      interval: 10s
      retries: 1
      start_period: 10s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/data"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/compose:/data/compose/1"
    networks:
      mac_vlan:
        ipv4_address: "${EXT_IPV4}"
      internal:


networks:
  internal:
    driver: "bridge"
  mac_vlan:
    driver: macvlan
    driver_opts:
      parent: "${MAC_VLAN_PARENT}"
    ipam:
      config:
      - subnet: "${IPAM_SUBNET}"
        gateway: "${IPAM_GATEWAY}"
        ip_range: "${IPAM_IP_RANGE}"
        aux_addresses:
          net_address: "${IPAM_NET_ADDRESS}"
