services:
  app:
    image: 'portainer/portainer-ee:2.45.1'
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${BASEPATH}/portainer/data:/data'
    networks:
      system_mac_vlan:
        ipv4_address: ${portainer_mac_vlan_ipv4}
      system_internal:


networks:
  system_internal:
    external: true
  system_mac_vlan:
    external: true
