version: '3'

services:
  broker:
    image: 'redis:7'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/broker:/data:Z'
    networks:
      - 'default'

  db:
    image: 'postgres:13'
    restart: 'unless-stopped'
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/db:/var/lib/postgresql/data:Z'
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
    networks:
      - 'default'

  gotenberg:
    image: 'gotenberg/gotenberg:7.8'
    restart: 'unless-stopped'
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    networks:
      - 'default'

  tika:
    image: 'ghcr.io/paperless-ngx/tika:latest'
    restart: 'unless-stopped'
    networks:
      - 'default'

  server:
    image: 'ghcr.io/paperless-ngx/paperless-ngx:latest'
    restart: 'unless-stopped'
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
#    ports:
#      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/data:/usr/src/paperless/data:Z'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/media:/usr/src/paperless/media:Z'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/export:/usr/src/paperless/export:Z'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/consume:/usr/src/paperless/consume:Z'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/trash:/media/trash:Z' ## the trash directory has to be writable by the user running docker-compose, with 755 permissions.
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://paperless_broker_1:6379
      PAPERLESS_DBHOST: paperless_db_1
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://paperless_gotenberg_1:3000
      PAPERLESS_TIKA_ENDPOINT: http://paperless_tika_1:9998
      PAPERLESS_CONSUMER_POLLING: 20
      PAPERLESS_APP_TITLE: "FairMarkt Paperless"
    networks:
      - 'default'
      - 'fm_internal'

networks:
  default:
  fm_internal:
    external: true
