version: '3'

services:
  broker:
    image: 'redis:6.0'
    restart: 'unless-stopped'
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/broker:/data'
    networks:
      - 'default'

  db:
    image: 'postgres:13'
    restart: 'unless-stopped'
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/db:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      - 'default'

  gotenberg:
    image: 'gotenberg/gotenberg:7.4'
    restart: 'unless-stopped'
    command:
      - "gotenberg"
      - "--chromium-disable-routes=true"
    networks:
      - 'default'

  tika:
    image: 'ghcr.io/paperless-ngx/tika:latest'
    restart: 'unless-stopped'
    networks:
      - 'default'

  server:
    image: 'ghcr.io/paperless-ngx/paperless-ngx:latest'
    restart: 'unless-stopped'
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
#    ports:
#      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - '${basepath}/${COMPOSE_PROJECT_NAME}/data:/usr/src/paperless/data'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/media:/usr/src/paperless/media'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/export:/usr/src/paperless/export'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/consume:/usr/src/paperless/consume'
      - '${basepath}/${COMPOSE_PROJECT_NAME}/trash:/media/trash'
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    networks:
      - 'default'
      - 'fm_internal'

networks:
  default:
  fm_internal:
    external: true
