#!/usr/bin/env bash
set -euo pipefail

# If TZ provided, configure container timezone (optional)
if [ -n "${TZ:-}" ]; then
  # update /etc/localtime if tzdata is present
  if [ -f "/usr/share/zoneinfo/${TZ}" ]; then
    ln -sf "/usr/share/zoneinfo/${TZ}" /etc/localtime
  else
    echo "Warning: timezone ${TZ} not found in container tzdata; leaving default"
  fi
fi

# Ensure output dir exists and is writable
mkdir -p "${OUTPUT_DIR:-/data}"
chown -R root:root "${OUTPUT_DIR:-/data}"

# Build crontab for root using CRON_SCHEDULE and run the script.
# Redirect job output to stdout/stderr so logs show up in container logs.
CRON="${CRON_SCHEDULE:-30 23 * * *}"
# write to /etc/crontabs/root (dcron style supports it)
cat > /etc/crontabs/root <<EOF
# generated by entrypoint
${CRON} /usr/local/bin/solar-fetch.sh >> /proc/1/fd/1 2>> /proc/1/fd/2
EOF

# Make sure crond runs as foreground
echo "Starting crond with schedule: ${CRON}"
exec crond -f -n
