---
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    command: hbbs
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    image: rustdesk/rustdesk-server:latest
    command: hbbr
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/root
    network_mode: "host"
    restart: unless-stopped
