version: '2.3' ## v2 is needet for networking, v2.3 is needet because of healt checks.
services:
#  unbound:
#    container_name: unbound
#    image: 'klutchell/unbound'
#    restart: 'always'
#    env_file:
#      - ./.env
#    hostname: unbound 
#    healthcheck:
#      test: ["CMD", "dig", "google.com", "@127.0.0.1"]
#      timeout: 2s
#      interval: 7s
#      retries: 1
#      start_period: 10s
#    dns: 
#      - '${dns_address_one}'
#      - '${dns_address_two}'
#    networks:
#      fm_internal:




