
version: '2.3' ## v2 is needet for networking, v2.3 is needet because of healt checks.

services:
 
 ## ------ DEPRECATED! ------ ## 
 ##  nginx-external:
 ##    container_name: nginx-external
 ##    image: 'jc21/nginx-proxy-manager:github-pr-1701'
 ##    restart: unless-stopped
 ## #    ports:
 ## #      - '80:80'
 ## #      - '81:81'
 ## #      - '443:443'
 ##    hostname: nginx-external
 ##    dns:
 ##      - 'pihole'
 ##      - '10.10.10.1'
 ##    volumes:
 ##      - /mnt/data/docker/nginx-external/data/:/data
 ##      - /mnt/data/docker/nginx-external/letsencrypt:/etc/letsencrypt
 ##    networks:
 ##      system_mac_vlan:
 ##        ipv4_address: 10.10.10.195
 ##      internal:
 ##    depends_on:
 ##      - pihole
 ##
 ##  nginx-internal:
 ##    container_name: nginx-internal
 ##    image: 'jc21/nginx-proxy-manager:github-pr-1701'
 ##    restart: unless-stopped
 ## #    ports:
 ## #      - '80:80'
 ## #      - '81:81'
 ## #      - '443:443'
 ##    hostname: xe
 ##    dns:
 ##      - 'pihole'
 ##      - '10.10.10.1'
 ##    volumes:
 ##      - /mnt/data/docker/nginx-internal/data/:/data
 ##      - /mnt/data/docker/nginx-internal/letsencrypt:/etc/letsencrypt
 ##    networks:
 ##      system_mac_vlan:
 ##        ipv4_address: 10.10.10.194
 ##      internal:
 ##    depends_on:
 ##      - pihole

  unbound:
    container_name: unbound
    image: 'klutchell/unbound'
#    volumes:
#      - '/mnt/data/docker/unbound:/etc/unbound'
#    ports:
#      - 53:53/udp
#      - 53:53/tcp
    hostname: unbound.xe
    healthcheck:
      test: ["CMD", "dig", "google.com", "@127.0.0.1"]
      timeout: 2s
      interval: 7s
      retries: 1
      start_period: 10s
    restart: always
    dns:
      - pihole
      - 10.10.10.1
    networks:
      internal:
  

  caddy:
    container_name: caddy
    image: 'caddy:latest'
    volumes:
      - '/mnt/data/docker/caddy/Caddyfile:/etc/caddy/Caddyfile'
      - '/mnt/data/docker/caddy/srv:/srv'
      - '/mnt/data/docker/caddy/data:/data'
      - '/mnt/data/docker/caddy/config:/config'
    hostname: caddy.xe
    restart: always
    dns:
      - pihole
      - 10.10.10.1
    networks:
      system_mac_vlan:
        ipv4_address: 10.10.10.13
      internal:
    depends_on:
      - pihole

  pihole:
    container_name: pihole
    image: 'pihole/pihole:latest'
    environment:
      - TZ=Europe/Berlin
      - VIRTUAL_HOST=pihole
      - PROXY_LOCATION=pihole
        #- WEBPASSWORD=lol
        #- ServerIP=127.0.0.1
    volumes:
      - '/mnt/data/docker/pihole/etc-pihole:/etc/pihole'
      - '/mnt/data/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
        #- '/mnt/data/docker/pihole/custom.list:/etc/pihole/custom.list'
        #- '/mnt/data/docker/pihole/05-pihole-custom-cname.conf:/etc/dnsmasq.d/05-pihole-custom-cname.conf'
    hostname: pihole
 #    ports:
 #      - '53:53/tcp'
 #      - '53:53/udp'
 #      - '80:80'
    restart: always
    dns:
      - '127.0.0.1'
      - '10.10.10.1'
    networks:
      system_mac_vlan:
        ipv4_address: 10.10.10.12
      internal:
    cap_add: #only needet if used as dhcp provider
      - NET_ADMIN 
    depends_on:
      - unbound
  
  kuma:
    container_name: kuma
    image: 'louislam/uptime-kuma:latest'
    volumes:
      - '/mnt/data/docker/kuma/app/data:/app/data'
 #    ports:
 #      - '3001:3001'
    hostname: kuma.xe
    restart: unless-stopped
    dns: 
      - pihole
      - 10.10.10.1
    networks:
      - internal
    depends_on:
      - pihole
      - caddy

  heimdall:
    container_name: heimdall
    image: 'linuxserver/heimdall:latest'
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - '/mnt/data/docker/heimdall/config:/config'
 #    ports:
 #      - 80:80
 #      - 443:443
    hostname: heimdall.xe
    restart: unless-stopped
    dns:
      - pihole
      - 10.10.10.1
    networks:
      - internal
    depends_on:
      - pihole
      - caddy

  pyload:
    image: linuxserver/pyload
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /mnt/data/docker/pyload/config:/config
      - /mnt/data/docker/pyload/downloads:/downloads
 #    ports:
 #      - 8000:8000
 #      - 7227:7227 #optional
    hostname: pyload.xe
    restart: unless-stopped
    dns:
      - pihole
      - 10.10.10.1
    networks:
      - internal
    depends_on:
      - caddy

  mkdocs:
    container_name: mkdocs
    image: 'polinux/mkdocs:arm64v8-1.1.2'
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
      ADD_MODULES: 'mkdocs-gitbook mkdocs-bootswatch fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material mkdocs-windmill-dark'
      FAST_MODE: 'true'
      DOCS_DIRECTORY: '/mkdocs'
      UPDATE_INTERVAL: 60
      AUTO_UPDATE: 'true'
    volumes:
      - /home/pi/.ssh/id_rsa:/root/.ssh/id_rsa
      - /mnt/data/docker/mkdocs/:/mkdocs
 #    ports:
 #      - '8000:8000'
    hostname: mkdocs.xe
    restart: unless-stopped
    dns:
      - pihole
      - 10.10.10.1
    networks:
      - internal
    depends_on:
      - caddy

networks:
  internal:
    driver: bridge
  system_mac_vlan:
    external: true



