services:
  app:
    image: 'jc21/nginx-proxy-manager:2.15.1'
    restart: always
    healthcheck:
      test: curl --fail http://127.0.1.1:81 || exit 1
      timeout: 2s
      interval: 7s
      retries: 1
      start_period: 10s
    volumes:
      - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/data/:/data'
      - '${BASEPATH}/${COMPOSE_PROJECT_NAME}/letsencrypt:/etc/letsencrypt'
    networks:
      system_mac_vlan:
        ipv4_address: ${NGINX_SYSTEM_MAC_VLAN_IPV4}
      system_internal:

networks:
  system_internal:
    external: true
  system_mac_vlan:
    external: true
