---
services:
  app:
    image: vikunja/vikunja:2.6.0
    env_file:
      - ".env"
      - "secrets.enc.env"
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/files:/app/vikunja/files
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/db:/db
    restart: unless-stopped
    networks:
      system_internal:

networks:
  system_internal:
    external: true
