services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nextcloud_aio_mastercontainer:/mnt/docker-aio-config"
    ports:
      #- "80:80"
      - "8080:8080"
      #- "8443:8443"
    environment:
       APACHE_IP_BINDING: 0.0.0.0
       APACHE_PORT: 11000
       NEXTCLOUD_DATADIR: "/sd/nc-data"
       SKIP_DOMAIN_VALIDATION: "true"
    security_opt: ["label:disable"]
  
  caddy:
     image: caddy:alpine
     restart: always
     container_name: caddy
     volumes:
       - ./Caddyfile:/etc/caddy/Caddyfile:z
       - ./certs:/certs:z
       - ./config:/config:z
       - ./data:/data:z
       - ./sites:/srv:Z
       #network_mode: host
     ports:
       - "80:80"
       - "443:443"


volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
