services:
  db:
    image: "mysql:oraclelinux8"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/db:/var/lib/mysql:z"
      - "./01-databases.sql:/docker-entrypoint-initdb.d/01-databases.sql"
    networks:
      - internal

  app:
    image: "wordpress:php8.2-apache"
    restart: unless-stopped
    #ports:
    #  - "8080:80"
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: "$DBHOST"
    depends_on:
      - db
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/app:/var/www/html:z"
    networks:
      - internal
      - fm_internal

  phpmyadmin:
    depends_on:
      - db
    image: "phpmyadmin:5-apache"
    restart: unless-stopped
    environment:
      PMA_HOST: "$DBHOST"
      PMA_USER: "$MYSQL_USER"
      PMA_PASSWORD: "$MYSQL_PASSWORD"
      PMA_ABSOLUTE_URI: "http://phpmyadmin.wordpress.fairmarkt"
      PMA_PMADB: "$MYSQL_DATABASE"
      PMA_CONTROLUSER: "$MYSQL_USER"
      PMA_CONTROLPASS: "$MYSQL_PASSWORD"
    #ports:
    #  - "8081:80"
    volumes:
      - "./phpmyadmin:/etc/phpmyadmin:ro"
    networks:
      - internal
      - fm_internal

networks:
  internal:
  fm_internal:
    external: true
