services:
  app:
    build: .
    restart: always
    env_file:
      - ".env"
    environment:
      - TZ=${TZ:-Europe/Berlin}
    volumes:
      - "./unbound.enc.conf:/etc/unbound/unbound.conf:ro"
    networks:
      system_mac_vlan:
        ipv4_address: "${EXT_IPV4}"
      bind_to_unbound:

networks:
  system_mac_vlan:
    external: true
  bind_to_unbound:
    external: true
