services:
  # ----------------------------------------------------------------------
  # COMMERCIAL & OTHER ADS-B FEEDERS
  # ----------------------------------------------------------------------
  piaware:
    image: ghcr.io/sdr-enthusiasts/docker-piaware:latest-build-665
    restart: unless-stopped
    env_file:
      - ".env"
      - "secrets.enc.env"
    ports:
      - 30105:30105
    networks:
      - system_internal
      - default
    tmpfs:
      - /run:exec,size=64M
      - /var/log

  fr24:
    image: ghcr.io/sdr-enthusiasts/docker-flightradar24:latest-build-858
    restart: unless-stopped
    env_file:
      - ".env"
      - "secrets.enc.env"
    ports:
      - 30108:30106
    networks:
      - system_internal
      - default
    tmpfs:
      - /var/log

  pfclient:
    image: ghcr.io/sdr-enthusiasts/docker-planefinder:latest-build-540
    env_file:
      - ".env"
      - "secrets.enc.env"
    restart: unless-stopped
    networks:
      - system_internal
      - default

  airnavradar:
    image: ghcr.io/sdr-enthusiasts/docker-airnavradar:latest-build-882
    env_file:
      - ".env"
      - "secrets.enc.env"
    restart: unless-stopped
    ports:
      - 30106:30105
    environment:
      - ALT=$${env.FEEDER_ALT_M}
    volumes: 
      - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp:roz
    tmpfs:
      - /run:exec,size=64M
      - /var/log

  planewatch:
    image: ghcr.io/plane-watch/docker-plane-watch:v0.0.9
    env_file:
      - ".env"
      - "secrets.enc.env"
    restart: unless-stopped
    ports:
      - 30107:30105
    entrypoint: ["/bin/sh", "-c", "export ALT=$$FEEDER_ALT_FT; exec /init"]
    environment:
      - DEBUG_LOGGING=true
    tmpfs:
      - /run:exec,size=64M
      - /var/log

  opensky:
    image: ghcr.io/sdr-enthusiasts/docker-opensky-network:latest-build-843
    restart: unless-stopped
    env_file:
      - ".env"
      - "secrets.enc.env"
    environment:
      - DEBUG_LOGGING=true
      - ALT=$${env.FEEDER_ALT_M}
    tmpfs:
      - /run:exec,size=64M
      - /var/log

##  adsbhub: ## Website not working, couldn't get key
##    image: ghcr.io/sdr-enthusiasts/docker-adsbhub:latest-build-517
##    restart: unless-stopped
##    environment:
##      - SBSHOST=${FEEDER_IP}
##      - CLIENTKEY=${ADSBHUB_STATION_KEY}

  # ----------------------------------------------------------------------
  # VISUALIZATION
  # ----------------------------------------------------------------------
  planefence:
    image: ghcr.io/sdr-enthusiasts/docker-planefence:latest-build-1220
    env_file:
      - ".env"
      - "secrets.enc.env"
    restart: unless-stopped
    networks:
      - system_internal
      - default
    environment:
      - ENABLE_WEB_CONFIG=true
      - PF_CONFIG_HTTP_PORT=9999
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/planefence/config:/usr/share/planefence/persist:z
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/planefence/html:/usr/share/planefence/html:z
    tmpfs:
      - /run:rw,nosuid,nodev,exec,relatime,size=256M
      - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M

  vrs:
    image: ghcr.io/sdr-enthusiasts/vrs:dev
    restart: unless-stopped
    networks:
      - system_internal
      - default
    ports:
      #- 8091:8091
       - 49000-49099:49000-49099
    environment:
       - VRS_CULTURE=en-GB
       - VRS_DB_UPDATE_POLICY_FULLAUTO=yes
       - VRS_DB_UPDATE_WITH_VACUUM=yes
       - VRS_DB_UPDATE_BACKUP_UNCOMPRESSED=yes
    tmpfs:
       - /tmp:rw,nosuid,nodev,noexec,relatime,size=128M
    volumes:
       - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/vrs:/root/.local/share/VirtualRadar
       - /etc/localtime:/etc/localtime:ro

networks:
  system_internal:
    external: true
