---
name: esptls
services:
  downloader:
    build: ./downloader
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data/raw:/data/raw
    env_file:
      - ".env"
      - "secrets.enc.env"

  scraper:
    build: ./scraper
    restart: unless-stopped
    env_file:
      - ".env"
      - "secrets.enc.env"

  processor:
    build: ./processor
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data/raw:/data/raw
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data/processed:/data/processed
    env_file:
      - ".env"
      - "secrets.enc.env"

  timelapse:
    build: ./timelapse
    restart: unless-stopped
    cpu_shares: 800 #default 1024, higher numbers = higher priority
    cpus: 3
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data/processed:/data/processed
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data/videos:/data/videos
    env_file:
      - ".env"
      - "secrets.enc.env"

  telegram-sender:
    build: ./sender
    restart: unless-stopped
    volumes:
      - ${BASEPATH}/${COMPOSE_PROJECT_NAME}/data/videos:/data/videos
    env_file:
      - ".env"
      - "secrets.enc.env"
