services:
  bind:
    image: ubuntu/bind9:9.20-24.10_beta
    environment:
      - BIND9_USER=root
      - TZ=Europe/Berlin
    volumes:
      - "./.config:/etc/bind"
      - "./.cache:/var/cache/bind"
      - "./.records:/var/lib/bind"
    restart: always
    networks:
      system_mac_vlan:
        ipv4_address: ${BIND_SYSTEM_MAC_VLAN_IPV4}
      system_internal:

networks:
  system_mac_vlan:
    external: true
  system_internal:
    external: true
