services:
  app:
    image: "louislam/uptime-kuma:2.3.0"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/app/data:/app/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    hostname: kuma.fairmarkt
    restart: unless-stopped
    networks:
      system_internal:

networks:
  system_internal:
    external: true
