#    hostname: kuma.home.arpa
#    restart: always
#    networks:
#      system_internal:
#      bookstack_default:
#
#networks:
#  system_internal:
#    external: true
#  bookstack_default:
#    external: true


services:
  app:
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data:/app/data
#      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/app/data"
#      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "3001:3001"

  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=kuma
      - MYSQL_USER=kuma
      - MYSQL_PASSWORD=kuma
      - MYSQL_ROOT_PASSWORD=kuma
    volumes:
      #- '${BASEPATH}/${COMPOSE_PROJECT_NAME}/mysql-data:/var/lib/mysql'
      - ./mysql:/var/lib/mysql
#    networks:
#      default:
