version: '3'
services:
  app:
    image: "louislam/uptime-kuma:latest"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/app/data"
    hostname: kuma.fairmarkt
    restart: unless-stopped
    networks:
      fm_internal:

networks:
  fm_internal:
    external: true
