version: '3'
services:
  searxng:
    container_name: 'searxng'
    image: 'searxng/searxng'
    restart: unless-stopped
    environment:
      - 'BASE_URL=http://searxng.xe:80/'
      - 'INSTANCE_NAME=xenon-searxng'
    volumes:
      - '/mnt/data/docker/searxng:/etc/searxng'
    networks:
      xe_internal:

networks:
  xe_internal:
    external: true
