version: '3'
services:
  app:
    image: 'searxng/searxng'
    restart: unless-stopped
    environment:
      - 'BASE_URL=https://searx.home.arpa'
      - 'INSTANCE_NAME=xenon-searx'
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}:/etc/searxng"
    networks:
      system_internal:

networks:
  system_internal:
    external: true
