services:
  app:
    build: .
    environment:
      TZ: "Europe/Brussels"
      CHANNELS: "${CHANNELS:-pietsmiet;linustech}" # ; separated
      DEFAULT_POLL_INTERVAL: "${DEFAULT_POLL_INTERVAL:-300}"         # seconds
      SCHEDULE_WINDOWS: "${SCHEDULE_WINDOWS:-Saturday:00:00-10:00:60}"  # day:start-end:interval (comma-separated for multiple)
      QUALITY: "best"
      DISABLE_ADS: "false"
      OUTPUT_DIR: "/data"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/data:/data"
    restart: unless-stopped

