services:
  db:
    image: "postgres:16-alpine3.22"
    restart: "unless-stopped"
    env_file:
      - ".env"
      - "secrets.enc.env"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/db:/var/lib/postgresql/data"
    networks:
      - "default"

  app:
    image: "vabene1111/recipes:2.6.11"
    restart: "unless-stopped"
    env_file:
      - ".env"
      - "secrets.enc.env"
    volumes:
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/staticfiles:/opt/recipes/staticfiles"
      - "${BASEPATH}/${COMPOSE_PROJECT_NAME}/mediafiles:/opt/recipes/mediafiles"
    depends_on:
      - "db"
    networks:
      - "default"
      - "system_internal"

networks:
  default:
  system_internal:
    external: true

