version: '3'
services:
  tandoor: ## Rezepte!
    container_name: tandoor
    image: 'vabene1111/recipes'
    env_file:
      - ./.env
      - ./.envp
    volumes:
      - '/mnt/data/docker/tandoor/staticfiles:/opt/recipes/staticfiles'
      - '/mnt/data/docker/tandoor/mediafiles:/opt/recipes/mediafiles'
    hostname: tandoor
    restart: unless-stopped
    dns:
      - pihole
      - 10.10.10.1
    networks:
      - internal
      - tandoor-db

  tandoor-db:
    container_name: tandoor-db
    image: 'postgres:11-alpine'
    env_file:
      - ./.env
      - ./.envp
    volumes:
      - '/mnt/data/docker/tandor-db/postgresql:/var/lib/postgresql/data'
    hostname: tandoor-db
    restart: unless-stopped
    dns: 
      - pihole
      - 10.10.10.1
    networks:
      - internal
    
networks:
  internal:
    driver: bridge
